### ISSUE TITLE
/useradjust.html doesn't work

### ISSUE THREAD

**Issue by Wouterr0** [zotion-site/zotion-site.github.io#1]
https://zotion-site.github.io/useradjust.html just shows an black rectangle however you adjust the sliders.
![image](https://user-images.githubusercontent.com/41055533/72223951-cd982480-3574-11ea-84e9-5ff0cd35f82c.png)

**Comment by Luigit12** [comment]
Scroll a little bit down. There is a third slider that you can adjust wich change the size of the balls.

**Comment by Wouterr0** [comment]
Bad website design
